[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
amm_with_transfer_hook = "F4RupoT7DMW6dDbkzoyG3R3LndyW9EJEeBp4FvMu9v56"

[programs.devnet]
amm_with_transfer_hook = "F4RupoT7DMW6dDbkzoyG3R3LndyW9EJEeBp4FvMu9v56"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
